require_relative '../vagrant/vagrant_utilities'

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.provision 'shell', inline: 'curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64 -o /usr/local/bin/goss; chmod +rx /usr/local/bin/goss'
end
