Vagrant.configure('2') do |config|
  config.landrush.enabled = true

  # icinga master
  config.vm.define 'master' do |master|
    master.vm.box = 'centos/7'
    master.vm.network 'private_network', ip: '192.168.33.10'
    master.vm.hostname = 'master.vagrant.test'

    # up the resources
    master.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
    end

    # install puppet
    master.vm.provision 'shell', inline: 'yum install rubygems -y; gem install --no-ri --no-rdoc puppet'
    # execute puppet
    master.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
    # remove puppet
    master.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; yum erase rubygems -y; yum autoremove -y'
  end

  # centos client
  config.vm.define 'client-centos' do |client_centos|
    client_centos.vm.box = 'centos/7'
    client_centos.vm.network 'private_network', ip: '192.168.33.11'
    client_centos.vm.hostname = 'client-centos.vagrant.test'

    # install puppet
    client_centos.vm.provision 'shell', inline: 'yum install rubygems -y; gem install --no-ri --no-rdoc puppet'
    # execute puppet
    client_centos.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
    # remove puppet
    client_centos.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; yum erase rubygems -y; yum autoremove -y'
  end

  # fedora client
  config.vm.define 'client-fedora' do |client_fedora|
    client_fedora.vm.box = 'fedora/24-cloud-base'
    client_fedora.vm.network 'private_network', ip: '192.168.33.12'
    client_fedora.vm.hostname = 'client-fedora.vagrant.test'

    # install puppet
    client_fedora.vm.provision 'shell', inline: 'dnf install rubygems -y; gem install --no-documentation puppet'
    # execute puppet
    client_fedora.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
    # remove puppet
    client_fedora.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; dnf erase rubygems -y; dnf autoremove -y'
  end

  # debian client
  config.vm.define 'client-debian' do |client_debian|
    client_debian.vm.box = 'debian/jessie64'
    client_debian.vm.network 'private_network', ip: '192.168.33.13'
    client_debian.vm.hostname = 'client-debian.vagrant.test'

    # install puppet
    client_debian.vm.provision 'shell', inline: 'apt-get install rubygems -y; gem install --no-ri --no-rdoc puppet'
    # execute puppet
    client_debian.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
    # remove puppet
    client_debian.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; apt-get remove rubygems -y; apt-get autoremove -y'
  end

  # ubuntu client
  config.vm.define 'client-ubuntu' do |client_ubuntu|
    client_ubuntu.vm.box = 'ubuntu/xenial64'
    client_ubuntu.vm.network 'private_network', ip: '192.168.33.14'
    client_ubuntu.vm.hostname = 'client-ubuntu.vagrant.test'

    # install puppet
    client_ubuntu.vm.provision 'shell', inline: 'apt-get install rubygems -y; gem install --no-ri --no-rdoc puppet'
    # execute puppet
    client_ubuntu.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
    # remove puppet
    client_ubuntu.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; apt-get remove rubygems -y; apt-get autoremove -y'
  end
end
