Vagrant.configure('2') do |config|
  config.landrush.enabled = true

  # icinga master
  config.vm.define 'master' do |master|
    master.vm.box = 'centos/7'
    master.vm.network 'private_network', ip: '192.168.33.10'
    master.vm.hostname = 'master.vagrant.test'

    # up the resources
    master.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
    end

    # install puppet
    master.vm.provision 'shell', inline: 'yum install rubygems -y; gem install --no-ri --no-rdoc puppet'
    # execute puppet
    master.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
    # remove puppet
    master.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; yum erase rubygems -y; yum autoremove -y'
  end

  # centos client
  config.vm.define 'centos' do |centos|
    centos.vm.box = 'centos/7'
    centos.vm.network 'private_network', ip: '192.168.33.11'
    centos.vm.hostname = 'centos.vagrant.test'
  end

  # fedora client
  config.vm.define 'fedora' do |fedora|
    fedora.vm.box = 'fedora/24-cloud-base'
    fedora.vm.network 'private_network', ip: '192.168.33.12'
    fedora.vm.hostname = 'fedora.vagrant.test'
  end

  # debian client
  config.vm.define 'debian' do |debian|
    debian.vm.box = 'debian/jessie64'
    debian.vm.network 'private_network', ip: '192.168.33.13'
    debian.vm.hostname = 'debian.vagrant.test'
  end

  # ubuntu client
  config.vm.define 'ubuntu' do |ubuntu|
    ubuntu.vm.box = 'ubuntu/xenial64'
    ubuntu.vm.network 'private_network', ip: '192.168.33.14'
    ubuntu.vm.hostname = 'ubuntu.vagrant.test'
  end
end
