Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'
  config.vm.network 'private_network', ip: '192.168.33.10'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '2'
    vb.memory = '2048'
  end

  # install puppet
  config.vm.provision 'shell', inline: 'yum install rubygems -y; gem install --no-ri --no-rdoc puppet'
  # execute puppet
  config.vm.provision 'shell', inline: '/usr/local/bin/puppet module install --modulepath=/vagrant puppetlabs-stdlib; /usr/local/bin/puppet apply --modulepath=/vagrant /vagrant/site.pp'
  # remove puppet
  config.vm.provision 'shell', inline: 'gem uninstall puppet facter hiera json_pure -aIx; yum erase rubygems -y; yum autoremove -y'
end
