Vagrant.configure('2') do |config|
  config.vm.box = 'fedora/24-cloud-base'
  config.vm.provision 'shell', inline: 'rpm -ivh https://packages.chef.io/files/stable/chefdk/1.3.40/el/7/chefdk-1.3.40-1.el7.x86_64.rpm'
end
