// post steps; terraform vars for platform; comments; puppet and chef; azure and do; serverspec and testinfra; packer and terraform should probably be cloned into branch dir; update terraform usage; terraform plan outputs need to be unique so config dirs need to be unique (or workspaces/branches/modules whatever) also terraform modifying same tfstate and hidden dirs not good
//@Library('jenkins-devops-libs@v1.0.0')_
library identifier: 'jenkins-devops-libs@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/mschuchard/jenkins-devops-libs.git'])

pipeline {
  agent any

  parameters {
    choice(name: 'PLATFORM', choices: 'All\nAWS\nAzure\nDO\nDocker\nVirtualbox', description: 'The platform to build for and deploy on.')
    string(name: 'SCM_URL', description: 'The URL (HTTPS or SSH URI) to the source repository containing the Packer template (should also contain provisioning and validation support code for the artifact).')
    string(name: 'TF_MOD_SCM_URL', description: 'The URL (HTTPS or SSH URI) to the source repository containing the Terraform module.')
  }

  stages {
    // passing creds to packer template from jenkins needs to be better so... vault time here too?; expand ansible to make it into webpage viewable demo and then expand goss
    stage('Build Artifact') {
      parallel {
        stage('Construct Amazon Linux AMI') {
          when { expression { return params.PLATFORM == 'All' || params.PLATFORM == 'AWS' } }
          stages {
            stage('Checkout Code') {
              steps {
                checkout([
                  $class: 'GitSCM',
                  doGenerateSubmoduleConfigurations: false,
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: params.SCM_URL]]])
              }
            }
            stage('Validate Template and Provision Code') {
              steps {
                script {
                  packer.validate {
                    template = 'lamp-cloud/packer.json'
                    only = 'amazon-ebs'
                  }
                }
                ansiblePlaybook(disableHostKeyChecking: true, extras: '--syntax-check', playbook: 'lamp-cloud/ansible/lamp.yml')
              }
            }
            stage('Build and Validate AMI') {
              script {
                packer.build {
                  template = 'lamp-cloud/packer.json'
                  only = 'amazon-ebs'
                }
              }
            }
          }
        }
        stage('Construct CentOS Azure VHD') {
          when { expression { return params.PLATFORM == 'All' || params.PLATFORM == 'Azure' } }
          stages {
            stage('Checkout Code') {
              steps {
                checkout([
                  $class: 'GitSCM',
                  doGenerateSubmoduleConfigurations: false,
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: params.SCM_URL]]])
              }
            }
            stage('Validate Template and Provision Code') {
              steps {
                script {
                  packer.validate {
                    template = 'lamp-cloud/packer.json'
                    only = 'azure-arm'
                  }
                }
                ansiblePlaybook(disableHostKeyChecking: true, extras: '--syntax-check', playbook: 'lamp-cloud/ansible/lamp.yml')
              }
            }
            stage('Build and Validate VHD') {
              script {
                packer.build {
                  template = 'lamp-cloud/packer.json'
                  only = 'azure-arm'
                }
              }
            }
          }
        }
        stage('Construct Ubuntu Droplet Image') {
          when { expression { return params.PLATFORM == 'All' || params.PLATFORM == 'DO' } }
          stages {
            stage('Checkout Code') {
              steps {
                checkout([
                  $class: 'GitSCM',
                  doGenerateSubmoduleConfigurations: false,
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: params.SCM_URL]]])
              }
            }
            stage('Validate Template and Provision Code') {
              steps {
                script {
                  packer.validate {
                    template = 'lamp-cloud/packer.json'
                    only = 'digitalocean'
                  }
                }
                ansiblePlaybook(disableHostKeyChecking: true, extras: '--syntax-check', playbook: 'lamp-cloud/ansible/lamp.yml')
              }
            }
            stage('Build and Validate Droplet') {
              script {
                packer.build {
                  template = 'lamp-cloud/packer.json'
                  only = 'digitalocean'
                }
              }
            }
          }
        }
        // docker and vbox
      }
    }
    stage('Deploy Artifact') {
      // Terraform should leverage vault for creds
      parallel {
        stage('Deploy EC2 with AMI') {
          when { expression { return params.PLATFORM == 'All' || params.PLATFORM == 'AWS' } }
          stages {
            stage('Checkout Code') {
              steps {
                checkout([
                  $class: 'GitSCM',
                  doGenerateSubmoduleConfigurations: false,
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: params.TF_MOD_SCM_URL]]])
              }
            }
            stage('Validate Config') {
              steps {
                script {
                  terraform.init('terraform')
                  terraform.plan('terraform')
                }
              }
            }
            // destroy first
            stage('Create EC2 with AMI') {
              script {
                terraform.apply('terraform/plan.tfplan')
              }
            }
          }
        }
        stage('Deploy VM with Azure VHD') {
          when { expression { return params.PLATFORM == 'All' || params.PLATFORM == 'Azure' } }
          stages {
            stage('Checkout Code') {
              steps {
                checkout([
                  $class: 'GitSCM',
                  doGenerateSubmoduleConfigurations: false,
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: params.TF_MOD_SCM_URL]]])
              }
            }
            stage('Validate Config') {
              steps {
                script {
                  terraform.init('terraform')
                  terraform.plan('terraform')
                }
              }
            }
            // destroy first; unsure what the minimum required resources are here
            stage('Create VM with VHD') {
              script {
                terraform.apply('terraform/plan.tfplan')
              }
            }
          }
        }
        stage('Deploy Droplet with Image') {
          when { expression { return params.PLATFORM == 'All' || params.PLATFORM == 'DO' } }
          stages {
            stage('Checkout Code') {
              steps {
                checkout([
                  $class: 'GitSCM',
                  doGenerateSubmoduleConfigurations: false,
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: params.TF_MOD_SCM_URL]]])
              }
            }
            stage('Validate Config') {
              steps {
                script {
                  terraform.init('terraform')
                  terraform.plan('terraform')
                }
              }
            }
            // destroy first
            stage('Create Droplet with DI') {
              script {
                terraform.apply('terraform/plan.tfplan')
              }
            }
          }
        }
        // docker and virtualbox
      }
    }
  }
}
