Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  config.vm.provision 'shell', inline: <<-SHELL
    cd sync
    sudo yum install ruby rubygems -y
    sudo gem build zauber-automato.gemspec
    sudo gem install --no-document zauber-automato*.gem
    sudo rm -f zauber-automato*.gem
    sudo rake spec/fixtures
  SHELL
end
