pipeline {
  agent any

  parameters {
    string(name: 'SCM_URL', description: 'The URL (HTTPS or SSH URI) to the source repository containing the Role.')
    string(name: 'CREDS', description: 'The Jenkins credentials id for the Ansible Playbook SSH.')
    string(name: 'NAME', defaultValue: 'Tomcat Hello', description: 'Unique descriptive name for the role deployment.')
    string(name: 'MSG', defaultValue: 'Hello World', description: 'Message for the Tomcat Application to display.')
  }

  stages {
    // checkout and build war file if desired
    stage('Checkout') {
      steps {
        print "Updating Role code for ${params.NAME}."
        checkout([
          $class: 'GitSCM',
          doGenerateSubmoduleConfigurations: false,
          extensions: [[$class: 'RelativeTargetDirectory',
            relativeTargetDir: params.NAME]],
          submoduleCfg: [],
          userRemoteConfigs: [[url: params.SCM_URL]]])
      }
    }
    stage('Test Role') {
      steps {
        print "Testing Role for ${params.NAME}."
        dir(params.NAME) {
          sh "ansible-galaxy -r requirements.yml --roles-path ."
          sh "molecule test"
        }
      }
    }
    stage('Deploy Role') {
      steps {
        print "Deploying ${params.NAME} role."
        dir(params.NAME) {
          ansiblePlaybook(credentialsId: params.CREDS, inventory: 'hosts', extraVars: "msg=${params.MSG}", playbook: 'playbook.yml')
        }
      }
    }
  }
  post {
    success {
      print "${params.NAME} role successfully deployed."
    }
    failure {
      print "Failure deploying ${params.NAME} role."
    }
  }
}
