#ARG registry
#FROM ${registry}/docker:stable
FROM docker:stable
WORKDIR /home
ENTRYPOINT ["docker", "run", "-dt", "--name"]
CMD ["app", "repo:tag"]

#FINISH
# needs volume mounts?
# better run flags/args?
