# Dependency and config checks
require_relative '../vagrant/vagrant_utilities'

plugins_install(%w[landrush])

# Configure boxes
Vagrant.configure('2') do |config|
  config.landrush.enabled = true

  config.vm.define 'master' do |master|
    master.vm.box = 'fedora/24-cloud-base'
    master.vm.network 'private_network', ip: '192.168.123.10'
    master.vm.hostname = 'master.vagrant.test'

    master.vm.provision 'shell', path: 'vagrant.sh'
    master.vm.provision 'shell', inline: 'dnf install -y rubygems; gem install --no-document serverspec rake'
  end

  (1..4).each do |i|
    config.vm.define "host#{i}" do |host|
      host.vm.box = 'centos/7'
      host.vm.network 'private_network', ip: "192.168.123.1#{i}"
      host.vm.hostname = "hostname#{i}.svr1122.vagrant.test"

      host.vm.provision 'shell', path: 'vagrant.sh'
    end
  end
end
