# vboxmanage list vms
# vagrant package --base vagrant_master_* --output master.box

# Dependency and config checks
Vagrant.require_version '>= 1.8.6'

raise 'Missing PE Master tarball.' if Dir.glob('puppet-enterprise-*-el-7-x86_64.tar.gz').empty?

# TODO: breaks on 1.9
unless Vagrant.has_plugin?('vagrant-pe_build')
  system 'sudo vagrant plugin install vagrant-pe_build'
  puts 'Rerun vagrant command to recognize installed plugin.'
  exit 0
end

# Configure boxes
Vagrant.configure('2') do |config|
  config.pe_build.version = '2016.4.2'
  # TODO: issues on 1.8.6 on mac osx
  config.vm.box = 'centos/7'
  config.pe_build.download_root = "file://#{Dir.pwd}"
  config.ssh.insert_key = false

  config.vm.define 'master' do |pm|
    pm.vm.network 'private_network', ip: '192.168.123.10'
    pm.vm.hostname = 'puppet.local'

    pm.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
    end

    pm.vm.provision 'shell', path: 'base.sh'
    pm.vm.provision 'shell', path: 'master.sh'
    pm.vm.provision :pe_bootstrap do |pe|
      pe.role = :master
    end
  end

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network 'private_network', ip: "192.168.123.1#{i}"
      node.vm.hostname = "node#{i}"

      node.vm.provision 'shell', path: 'base.sh'
      node.vm.provision :pe_agent do |pe|
        pe.master_vm = 'master'
      end
      node.vm.provision 'shell', inline: 'systemctl disable puppet; systemctl stop puppet'
    end
  end
end
